package api

import (
	"go_stock_analysis/registry"
	"go_stock_analysis/server/api/handler"
	"net/http"

	"github.com/go-chi/chi"
)

const (
	contentTypeHeaderKey = "Content-Type"
	contentType          = "application/json; charset=utf-8"
)

// serverImpl Implementation of ServerInterface generated by oapi-codegen command.
type serverImpl struct {
	db registry.Registry
}

// 株価取得
// (GET /stock)
func (s *serverImpl) AP01GetStock(w http.ResponseWriter, r *http.Request, params handler.AP01GetStockParams) {
	if err := handler.HandleGetStockRequest(w, r, params, s.db.DB()); err != nil {
		msg := err.Error()
		http.Error(w, msg, http.StatusInternalServerError)
	}
}

// 株式データ登録
// (POST /stock)
func (s *serverImpl) AP01PostStock(w http.ResponseWriter, r *http.Request) {
	if err := handler.HandlePostStockRequest(w, r, s.db.DB()); err != nil {
		msg := err.Error()
		http.Error(w, msg, http.StatusInternalServerError)
	}
}

// RegisterHandlers APIのハンドラを登録する
func RegisterHandlers(registry registry.Registry, router *chi.Mux) {
	handler.HandlerFromMux(createServerInterface(registry), router)
}

func createServerInterface(registry registry.Registry) handler.ServerInterface {
	return &serverImpl{
		db: registry,
	}
}
