version: "3"
services:
  db:
    build:
      context: "./mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"
  dev:
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - "./:/app"
    tty: true
    environment:
      - "DB_USER=root"
      - "DB_PASSWORD=password"
      - "DB_HOST=db"
      - "DB_NAME=go_stock_analysis"
      - "API_KEY=demo"
