// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

var TableNames = struct {
	Intervals string
	Price     string
	Stocks    string
}{
	Intervals: "intervals",
	Price:     "price",
	Stocks:    "stocks",
}
